spring.application.name=app

# --- DataSource Configuration ---
spring.datasource.url=jdbc:sqlite:./data/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# --- Hibernate / JPA Configuration ---
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# --- Logging ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# --- Thymeleaf Configuration ---
spring.mvc.hiddenmethod.filter.enabled=true


spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

logging.level.com.regifted.app=INFO

