spring.application.name=app

# --- DataSource Configuration ---
spring.datasource.url=jdbc:sqlite:./data/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# --- Hibernate / JPA Configuration ---
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# --- Logging ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT Configuration ---
app.jwt.secret=NHhK*gkIp%%QJ%#!mFyWfBNgMSMs@zsWyf9MS3mS
app.jwt.expiration-ms=3600000

# --- Bean Definition Overriding ---
spring.main.allow-bean-definition-overriding=true

