

### get cart
POST http://localhost:8080/cart/
Content-Type: application/json
Authorization: Basic YWRtaW5AYWRtaW4uZnI6YWRtaW5wYXNz

{
  "title": "Lamp",
  "description": "Une superbe lamp en bois",
  "latitude": 48.0,
  "longitude": 40.0,
  "state": "USED",
  "keywords": ["lamp", "bois", "recyclé"]
}