### GET JSON
GET http://localhost:8080/items
Accept: application/json



### GET HTML
GET http://localhost:8080/items
Accept: text/html



### PUT update item
PUT http://localhost:8080/items/update/e8ba9228-35f3-47a8-b54b-a8180cb09ea2
Content-Type: application/json
Accept: application/json

{
  "title": "Mon objet mis à jour",
  "description": "Description mise à jour de l'objet",
  "latitude": 45,
  "longitude": 6,
  "state": "USED"
}


### Create a new Item
POST http://localhost:8080/items
Content-Type: application/json

{
  "title": "Chaise en bois",
  "description": "Une chaise solide en chêne massif, légèrement usée mais encore en bon état.",
  "latitude": 48,
  "longitude": 40,
  "state": "USED",
  "keywords": ["meuble", "bois", "recyclé"]
}


### Get item
GET http://localhost:8080/items/b3d07fac-1d1d-4870-bbf1-69966b416077
Accept: text/html
